### ISSUE TITLE
There is a bug in dataset maybe. Might cause over-fitting maybe.

### ISSUE THREAD

**Issue by truman1211** [SwinTransformer/AiT#3]
Thanks for yours sharing. 

        transform = [
            A.Crop(x_min=41, y_min=0, x_max=601, y_max=480),
            A.HorizontalFlip(),
            A.RandomCrop(crop_size[0], crop_size[1]),
        ]

In dataset./nyudepthv2.py ,  i found you cropped image to (480,480)[fixed region], after that a randomcrop is used.
Maybe albumentations could change the transform sequence？ 
I am not sure.

**Comment by hust-nj** [comment]
Hi, `A.Crop(x_min=41, y_min=0, x_max=601, y_max=480)` crops the image to `(560, 480)` rather than `(480, 480)`.

**Comment by truman1211** [comment]
embarrassing
