### ISSUE TITLE
'PublicAccessNotPermitted' when download the checkpoints

### ISSUE THREAD

**Issue by xuanlongORZ** [SwinTransformer/AiT#7]
Hi, thank you for the excellent work!
I come across some troubles when I download the checkpoints using wget, it raises an error 'PublicAccessNotPermitted'. I would like to know how to download them properly, especially the pre-trained backbone models.
Thank you in advance!

**Comment by Sivloc** [comment]
Yes I have exactly the same problem, i was looking for another source but didn't find any .

**Comment by hust-nj** [comment]
Hi, you can access them now by adding sas token in url.
https://github.com/SwinTransformer/AiT/commit/3527d503e24d560e52fa2fa0528f678a1f9d0533

**Comment by xuanlongORZ** [comment]
It works, thanks a lot !
